import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div>TNF</div>
          <nav>
            <div>보드게임</div>
            <div>새소식</div>
            <div>소개</div>
          </nav>
          <div>
            <div>장바구니</div>
            <div>로그인</div>
          </div>
        </header>
        {children}
        <footer>
        </footer>
      </body>
    </html>
  );
}
